set(CUSTOM_SERVER_MODULES "")
set(EXECUTABLE MyFancyServer)
set(SERVER_INCLUDE_DIRECTORIES "/home/pnikiel/include" )
set(SERVER_LINK_LIBRARIES -lxxx )
set(SERVER_LINK_DIRECTORIES "/home/pnikiel/lib" )
