/*
 * BuildMetaInfo.cpp
 *
 *  Created on: Mar 25, 2016
 *      Author: bfarnham
 */
#include "MetaBuildInfo.h"
#include "MetaBuildInfoGenerated.h" // contains constants; contents generated by meta_build_info.py at build time.

using std::string;

string BuildMetaInfo::getBuildTime()
{
	return GEND_BUILD_TIME;
}

string BuildMetaInfo::getBuildHost()
{
	return GEND_BUILD_HOST;
}

std::string BuildMetaInfo::getCommitID()
{
	return GEND_COMMIT_ID;
}

string BuildMetaInfo::getToolkitLibs()
{
	return GEND_TOOLKIT_LIBS;
}
