jobs:
  include:

    - name: uasdk_default_quasar_design
      script:
        - docker run --interactive --tty pnikiel/quasar:quasar-uasdk /bin/bash -c "
            git clone --recursive -b ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} --depth=1 https://github.com/quasar-team/quasar.git ;
            cd quasar ;
            .CI/run_test_case.py --opcua_backend uasdk --compare_with_nodeset .CI/test_cases/test_default_quasar_design/reference_ns2.xml ;
            "

    - name: uasdk_test_sync_methods
      script:
        - docker run --interactive --tty pnikiel/quasar:quasar-uasdk /bin/bash -c "
            git clone --recursive -b ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} --depth=1 https://github.com/quasar-team/quasar.git ;
            cd quasar ;
            .CI/run_test_case.py --opcua_backend uasdk --design .CI/test_cases/test_methods/Design.xml --generate_all_devices --config .CI/test_cases/test_methods/config.xml --compare_with_nodeset .CI/test_cases/test_methods/reference_ns2.xml ;
            "

    - name: uasdk_test_async_methods
      script:
        - docker run --interactive --tty pnikiel/quasar:quasar-uasdk /bin/bash -c "
            git clone --recursive -b ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} --depth=1 https://github.com/quasar-team/quasar.git ;
            cd quasar ;
            .CI/run_test_case.py --opcua_backend uasdk --design .CI/test_cases/test_async_methods/Design.xml --generate_all_devices --config .CI/test_cases/test_async_methods/config.xml --compare_with_nodeset .CI/test_cases/test_methods/reference_ns2.xml
            "

    - name: uasdk_test_cache_variables
      script:
        - docker run --interactive --tty pnikiel/quasar:quasar-uasdk /bin/bash -c "
            git clone --recursive -b ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} --depth=1 https://github.com/quasar-team/quasar.git ;
            cd quasar ;
            cp .CI/test_cases/test_cache_variables/Design.xml Design ;
            ./quasar.py generate device --all ;
            ./quasar.py set_build_config .CI/travis/build_configs/uasdk-eval.cmake ;
            ./quasar.py build ;
            cp .CI/test_cases/test_cache_variables/DTestClass.test.h Device/include/DTestClass.h ;
            cp .CI/test_cases/test_cache_variables/DTestClass.test.cpp Device/src/DTestClass.cpp ;
            cp -v .CI/test_cases/test_cache_variables/config.xml build/bin ;
            ./quasar.py build ;
            ./.CI/travis/server_fixture.py --command_to_run uasak_dump ;
            /opt/NodeSetTools/nodeset_compare.py .CI/test_cases/test_cache_variables/reference_ns2.xml build/bin/dump.xml --ignore_nodeids StandardMetaData ;
            "

    - name: uasdk_test_source_variables
      script:
        - docker run --interactive --tty pnikiel/quasar:quasar-uasdk /bin/bash -c "
            git clone --recursive -b ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} --depth=1 https://github.com/quasar-team/quasar.git ;
            cd quasar ;
            .CI/run_test_case.py --opcua_backend uasdk --design .CI/test_cases/test_source_variables/Design.xml --generate_all_devices --config .CI/test_cases/test_source_variables/config.xml --compare_with_nodeset .CI/test_cases/test_source_variables/reference_ns2.xml
            "

    - name: uasdk_test_config_entries
      script:
        - docker run  --interactive --tty pnikiel/quasar:quasar-uasdk /bin/bash -c "
            git clone --recursive -b ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} --depth=1 https://github.com/quasar-team/quasar.git ;
            cd quasar ;
            .CI/run_test_case.py --opcua_backend uasdk --design .CI/test_cases/test_config_entries/Design.xml --generate_all_devices --config .CI/test_cases/test_config_entries/config.xml --compare_with_nodeset .CI/test_cases/test_config_entries/reference_ns2.xml
            "
    - name: uasdk_test_calculated_variables
      script:
        - docker run  --interactive --tty pnikiel/quasar:quasar-uasdk /bin/bash -c "
            echo branch ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} ;
            git clone --recursive -b ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} --depth=1 https://github.com/quasar-team/quasar.git ;
            cd quasar ;
            .CI/run_test_case.py --opcua_backend uasdk --open62541_compat_branch ${OPEN62541_COMPAT_VERSION} --design .CI/test_cases/test_calculated_variables/Design.xml --config .CI/test_cases/test_calculated_variables/config.xml --compare_with_nodeset .CI/test_cases/test_calculated_variables/reference_ns2.xml ;"
