
/*  © Copyright CERN, 2015. All rights not expressly granted are reserved.

    The stub of this file was generated by quasar (https://github.com/quasar-team/quasar/)

    Quasar is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public Licence as published by
    the Free Software Foundation, either version 3 of the Licence.
    Quasar is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public Licence for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with Quasar.  If not, see <http://www.gnu.org/licenses/>.


 */


#ifndef __DLogLevel__H__
#define __DLogLevel__H__

#include <Base_DLogLevel.h>
#include <LogIt.h>


namespace Device
{

class
    DLogLevel
    : public Base_DLogLevel
{

public:
    /* sample constructor */
    explicit DLogLevel (
        const Configuration::LogLevel& config,
        Parent_DLogLevel* parent
    ) ;
    /* sample dtr */
    ~DLogLevel ();

    /* delegators for
    cachevariables and sourcevariables */
    /* Note: never directly call this function. */
    UaStatus writeLogLevel ( const UaString& v);


    /* delegators for methods */

private:
    /* Delete copy constructor and assignment operator */
    DLogLevel( const DLogLevel& other );
    DLogLevel& operator=(const DLogLevel& other);

    // ----------------------------------------------------------------------- *
    // -     CUSTOM CODE STARTS BELOW THIS COMMENT.                            *
    // -     Don't change this comment, otherwise merge tool may be troubled.  *
    // ----------------------------------------------------------------------- *

public:

private:
    const std::string m_componentName;



};

}

#endif // __DLogLevel__H__